[workspace]
members = [
    'xtask',
    'openvr-driver-sys',
    'ovr-mobile-sdk-sys',
    'common',
    'server_bootstrap',
    'server_driver',
    'server_gui',
    'client_hmd',
    'client_tracker',
]