[package]
name = 'openvr-driver'
version = '0.1.8'
authors = ['Riccardo Zaglia <github.com/zarik5>']
license = 'MIT'
edition = '2018'

[lib]
crate-type = ['rlib']

[dependencies]
paste = '0.1.6'
lazy_static = '1.4.0'
openvr-driver-sys = { path = '../openvr-driver-sys' }
