[package]
name = 'playground'
version = '0.1.0'
authors = ['Riccardo Zaglia <github.com/zarik5>']
license = 'MIT'
edition = '2018'

[dependencies]
bridgevr_common = { path = '../common' }
winit = "0.22.0"
ash = "0.29.0"
parking_lot = "0.10.0"