[package]
name = 'bridgevr_server_gui'
version = '0.1.0-alpha.0'
authors = ['zarik5 <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
serde_json = '1.0'
bridgevr_xtask = { path = '../xtask' }
iced = '0.1.0'

[build-dependencies]
bridgevr_common = { path = '../common' }