[package]
name = 'ovr-mobile-sdk-sys'
version = '0.12.0'
authors = ['Riccardo Zaglia <github.com/zarik5>']
license = 'MIT'
edition = '2018'
build = 'build.rs'

[lib]
crate-type = ['rlib']

[build-dependencies]
bindgen = '0.53.1'