[package]
name = 'settings-schema'
version = '0.1.0'
authors = ['zarik5 <riccardo.zaglia5@gmail.com>']
license = 'MIT'
edition = '2018'

[dependencies]
serde = '^1.0'
serde_json = '^1.0'
settings-schema-derive = { path = '../settings-schema-derive'}