[package]
name = 'openvr-driver-sys'
version = '0.1.9'
authors = ['Riccardo Zaglia <github.com/zarik5>']
license = 'MIT'
edition = '2018'
build = 'build.rs'

[lib]
crate-type = ['rlib']

[build-dependencies]
bindgen = '0.53.0'
cc = '1.0.50'
regex = '1.3.4'